/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "EmptyAction"
  | "CubeAction.003"
  | "Cube.001Action.001"
  | "Cube.002Action.001"
  | "Cube.004Action.001"
  | "Cube.005Action.001"
  | "Cube.006Action.001"
  | "Cube.007Action.001"
  | "Cube.008Action.001"
  | "Cube.009Action.001"
  | "Cube.010Action.001"
  | "Cube.011Action.001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/3d_pyramid.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Empty"
          position={[-0.128, 0.03, -0.341]}
          rotation={[0, -0.153, 0]}
        >
          <mesh
            name="Cube"
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={materials.Material}
            position={[1.802, 1.818, -1.895]}
          />
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.Material}
            position={[0.191, 0.383, -4.952]}
          />
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.Material}
            position={[1.95, 2.034, -2.73]}
          />
          <group name="Cube003" position={[-0.001, 1.555, 0.002]} />
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.Material}
            position={[1.73, 1.334, -2.132]}
          />
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Material}
            position={[1.658, 1.139, -2.322]}
          />
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.Material}
            position={[2.366, 1.474, -1.946]}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.Material}
            position={[2.081, 1.001, -1.621]}
          />
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.Material}
            position={[1.066, 2.362, -3.026]}
          />
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials.Material}
            position={[2.084, 1.552, -2.2]}
          />
          <mesh
            name="Cube010"
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={materials.Material}
            position={[1.95, 0.39, -2.079]}
          />
          <mesh
            name="Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials.Material}
            position={[2.912, 0.349, -1.732]}
          />
        </group>
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
          position={[-3.456, -0.575, -0.258]}
          rotation={[-0.007, 0.682, 0]}
          scale={6.555}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d_pyramid.glb");